start		192.168.42.2
end		192.168.42.242
interface	usb0
max_leases	32
auto_time	3600
lease_file	/var/lib/misc/udhcpd-ncm.leases
pidfile		/var/run/udhcpd-ncm.pid
option	subnet	255.255.255.0
option	lease	3600
